# Generated by Django 5.2.7 on 2026-06-16 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=150)),
                ("telephone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("specialite", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=150)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("sexe", models.CharField(max_length=10)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiants",
                        to="core.classe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=10)),
                ("moyenne_generale", models.FloatField(default=0)),
                ("rang", models.IntegerField(blank=True, null=True)),
                ("mention", models.CharField(blank=True, max_length=50)),
                ("decision_jury", models.CharField(blank=True, max_length=100)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.etudiant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classe",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.filiere"
            ),
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.classe"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.etudiant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=150)),
                ("coefficient", models.IntegerField(default=1)),
                ("volume_horaire", models.IntegerField(default=0)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.filiere"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classe",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.niveau"
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=10)),
                ("cc", models.FloatField(default=0)),
                ("devoir", models.FloatField(default=0)),
                ("examen", models.FloatField(default=0)),
                ("moyenne", models.FloatField(blank=True, null=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.etudiant"
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.matiere"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AffectationMatiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.classe"
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.matiere"
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.professeur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("prof", "Professeur"),
                            ("etudiant", "Etudiant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
