# Generated by Django 5.2.7 on 2026-06-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filierebts'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='filiere_bts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filierebts'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere_bts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filierebts', verbose_name='Filière BTS'),
        ),
    ]
