# Generated by Django 5.2.7 on 2026-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_etudiant_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='filiere',
        ),
    ]
