# Generated by Django 5.2.7 on 2026-06-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_classe_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='filiere',
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere_bts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.filierebts'),
            preserve_default=False,
        ),
    ]
