# Generated by Django 5.2.15 on 2026-07-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categorie_matiere_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieNotesBTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies_notes', to='core.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='saisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.saisienotesbts'),
        ),
    ]
