# Generated by Django 5.2.15 on 2026-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_saisienotesbts_note_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='filierebts',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='filieres_bts', to='core.niveau'),
        ),
    ]
