# Generated by Django 5.2.15 on 2026-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_filierebts_niveaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=2),
        ),
    ]
