# Generated by Django 5.2.15 on 2026-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_note_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='saisienotesbts',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
    ]
