# Generated by Django 5.2.15 on 2026-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bulletin_annee_academique_classe_annee_academique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
