# Generated by Django 5.2.15 on 2026-07-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_etudiant_lieu_naissance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau', 'nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere_bts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filierebts', verbose_name='Filière BTS'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveau', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salle', verbose_name='Salle'),
        ),
    ]
