# Generated by Django 5.2.15 on 2026-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_classe_options_alter_classe_annee_academique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('prof', 'Professeur'), ('etudiant', 'Etudiant'), ('GESTIONNAIRE', 'Gestionnaire')], max_length=20),
        ),
    ]
