# Generated by Django 5.2.7 on 2026-08-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandeUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage de la grande unité")),
                ('description', models.TextField(blank=True, null=True)),
                ('filiere_bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandes_unites', to='core.filierebts')),
            ],
            options={
                'verbose_name': 'Grande unité',
                'verbose_name_plural': 'Grandes unités',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='grande_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='core.grandeunite'),
        ),
        migrations.CreateModel(
            name='MatiereAAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('coefficient', models.IntegerField(default=1)),
                ('volume_horaire', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorie')),
                ('filiere_bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filierebts')),
            ],
        ),
    ]
