# Generated by Django 5.2.7 on 2026-09-01 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_grandeunite_matiere_grande_unite_matiereaaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiereaaa',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='matiereaaa',
            name='filiere_bts',
        ),
        migrations.AddField(
            model_name='grandeunite',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandes_unites', to='core.niveau'),
        ),
        migrations.AlterField(
            model_name='grandeunite',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='grandeunite',
            constraint=models.UniqueConstraint(fields=('filiere_bts', 'niveau', 'code'), name='unique_grande_unite_filiere_niveau_code'),
        ),
        migrations.DeleteModel(
            name='MatiereAAA',
        ),
    ]
