# Generated by Django 5.2.7 on 2026-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauLMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
