# Generated by Django 5.2.7 on 2026-06-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0002_niveaulmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiliereLMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseLMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='lmd.niveaulmd')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='lmd.filierelmd')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
    ]
