# Generated by Django 5.2.7 on 2026-06-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0003_filierelmd_classelmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelmd',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_lmd', to='lmd.etudiantlmd'),
        ),
    ]
