# Generated by Django 5.2.7 on 2026-06-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0004_alter_notelmd_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecue',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
