# Generated by Django 5.2.7 on 2026-06-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0005_ecue_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiantlmd',
            name='classe',
        ),
    ]
