# Generated by Django 5.2.7 on 2026-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0006_remove_etudiantlmd_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantlmd',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=10),
        ),
    ]
