# Generated by Django 5.2.7 on 2026-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0007_alter_etudiantlmd_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantlmd',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
