# Generated by Django 5.2.7 on 2026-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0008_etudiantlmd_lieu_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantlmd',
            name='statut',
            field=models.CharField(choices=[('AF', 'Affecté'), ('NF', 'Non Affecté')], default='NF', max_length=2),
        ),
    ]
