# Generated by Django 5.2.15 on 2026-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0009_etudiantlmd_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantlmd',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=10),
        ),
    ]
