# Generated by Django 5.2.15 on 2026-06-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0010_alter_etudiantlmd_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandeUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('semestre', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='notelmd',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], default='S1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notelmd',
            name='session',
            field=models.CharField(choices=[('1', 'Session 1'), ('2', 'Session 2 (Rattrapage)')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='ue',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.filierelmd'),
        ),
        migrations.AddConstraint(
            model_name='notelmd',
            constraint=models.UniqueConstraint(fields=('etudiant', 'ecue', 'semestre', 'session'), name='unique_note_par_session'),
        ),
        migrations.AddField(
            model_name='grandeunite',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.filierelmd'),
        ),
        migrations.AddField(
            model_name='ue',
            name='grande_unite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='lmd.grandeunite'),
            preserve_default=False,
        ),
    ]
