# Generated by Django 5.2.15 on 2026-06-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0011_grandeunite_notelmd_semestre_notelmd_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmd.filierelmd'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='grande_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='lmd.grandeunite'),
        ),
    ]
