# Generated by Django 5.2.7 on 2026-06-29 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0012_alter_ue_filiere_alter_ue_grande_unite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaisieNoteLMD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niveau", models.CharField(max_length=10)),
                ("semestre", models.CharField(max_length=2)),
                ("session", models.CharField(default="1", max_length=1)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ecue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lmd.ecue"
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lmd.filierelmd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaisieNoteLMDItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cc", models.FloatField(default=0)),
                ("examen", models.FloatField(default=0)),
                ("moyenne", models.FloatField(blank=True, null=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.etudiantlmd",
                    ),
                ),
                (
                    "saisie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lmd.saisienotelmd",
                    ),
                ),
            ],
            options={
                "unique_together": {("saisie", "etudiant")},
            },
        ),
    ]
