# Generated by Django 5.2.7 on 2026-07-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0013_saisienotelmd_saisienotelmditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiantlmd",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lmd.filierelmd"
            ),
        ),
    ]
