# Generated by Django 5.2.7 on 2026-07-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0014_alter_etudiantlmd_filiere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classelmd",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ClasseLMD",
                to="lmd.filierelmd",
            ),
        ),
        migrations.AlterField(
            model_name="classelmd",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ClasseLMD",
                to="lmd.niveaulmd",
            ),
        ),
    ]
