# Generated by Django 5.2.7 on 2026-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0015_alter_classelmd_filiere_alter_classelmd_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiantlmd",
            name="ecues",
            field=models.ManyToManyField(blank=True, to="lmd.ecue"),
        ),
        migrations.AddField(
            model_name="etudiantlmd",
            name="ues",
            field=models.ManyToManyField(blank=True, to="lmd.ue"),
        ),
    ]
