# Generated by Django 5.2.15 on 2026-07-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0016_etudiantlmd_ecues_etudiantlmd_ues'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('type_session', models.CharField(choices=[('NORMALE', 'Session normale'), ('RATTRAPAGE', 'Session de rattrapage')], max_length=20)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], max_length=2)),
                ('annee_academique', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiantlmd',
            name='ecues',
        ),
        migrations.RemoveField(
            model_name='etudiantlmd',
            name='ues',
        ),
        migrations.AddField(
            model_name='filierelmd',
            name='niveau_formation',
            field=models.CharField(choices=[('L1-L2', 'Licence Fondamentale'), ('L3', 'Licence Professionnelle'), ('M1-M2', 'Master')], default='L1-L2', max_length=10),
        ),
        migrations.AddField(
            model_name='saisienotelmd',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecue',
            name='credit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saisienotelmditem',
            name='moyenne',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lmd.filierelmd'),
        ),
        migrations.CreateModel(
            name='CandidatRattrapage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=2)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('annee_academique', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ancienne_note', models.FloatField(default=0)),
                ('nouvelle_note', models.FloatField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.ecue')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rattrapages', to='lmd.etudiantlmd')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.sessionacademique')),
            ],
            options={
                'unique_together': {('etudiant', 'ecue', 'semestre', 'annee_academique')},
            },
        ),
    ]
