# Generated by Django 5.2.15 on 2026-07-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0017_sessionacademique_remove_etudiantlmd_ecues_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatrattrapage',
            unique_together={('etudiant', 'ecue', 'session', 'annee_academique')},
        ),
        migrations.AlterField(
            model_name='candidatrattrapage',
            name='ecue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats_rattrapage', to='lmd.ecue'),
        ),
        migrations.AlterField(
            model_name='candidatrattrapage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats_rattrapage', to='lmd.etudiantlmd'),
        ),
        migrations.AlterField(
            model_name='candidatrattrapage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='lmd.sessionacademique'),
        ),
        migrations.RemoveField(
            model_name='candidatrattrapage',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='candidatrattrapage',
            name='valide',
        ),
    ]
