# Generated by Django 5.2.15 on 2026-07-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0018_alter_candidatrattrapage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiantlmd',
            options={'ordering': ['nom', 'prenoms']},
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='annee_academique',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='lmd.filierelmd'),
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='matricule',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiantlmd',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_lmd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='etudiantlmd',
            constraint=models.UniqueConstraint(fields=('matricule', 'annee_academique'), name='unique_etudiant_annee'),
        ),
    ]
