# Generated by Django 5.2.7 on 2026-07-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0019_alter_etudiantlmd_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnneeAcademique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=20)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EnseignantLMD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("grade", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("libelle", models.CharField(max_length=50)),
                ("ordre", models.IntegerField(default=1)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deliberation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moyenne_generale", models.FloatField()),
                ("resultat", models.CharField(max_length=30)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.etudiantlmd",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AffectationECUE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ecue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lmd.ecue"
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.enseignantlmd",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscriptionLMD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niveau", models.CharField(max_length=10)),
                ("statut", models.CharField(default="INSCRIT", max_length=20)),
                (
                    "annee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.anneeacademique",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.etudiantlmd",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lmd.filierelmd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValidationUE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moyenne", models.FloatField()),
                ("valide", models.BooleanField()),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lmd.etudiantlmd",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lmd.ue"
                    ),
                ),
            ],
        ),
    ]
