# Generated by Django 5.2.7 on 2026-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0020_anneeacademique_enseignantlmd_semestre_deliberation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notelmd",
            name="semestre",
            field=models.CharField(
                choices=[
                    ("S1", "Semestre 1"),
                    ("S2", "Semestre 2"),
                    ("S3", "Semestre 3"),
                    ("S4", "Semestre 4"),
                    ("S5", "Semestre 5"),
                    ("S6", "Semestre 6"),
                ],
                default="S1",
                max_length=2,
            ),
        ),
    ]
