# Generated by Django 5.2.7 on 2026-07-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0021_alter_notelmd_semestre"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteLMDEN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ecue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_en",
                        to="lmd.ecue",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_lmd_en",
                        to="lmd.etudiantlmd",
                    ),
                ),
            ],
        ),
    ]
