# Generated by Django 5.2.15 on 2026-07-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0022_notelmden'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MasterProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='lmd.filierelmd')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=1)),
                ('niveau', models.CharField(max_length=2)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.masterprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='MasterUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('credit', models.IntegerField(default=0)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4')], max_length=2)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='lmd.masterprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='MasterECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('coefficient', models.IntegerField(default=1)),
                ('credit', models.IntegerField(default=0)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='lmd.masterue')),
            ],
        ),
        migrations.CreateModel(
            name='NoteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.FloatField(default=0)),
                ('examen', models.FloatField(default=0)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.masterecue')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.etudiantmaster')),
            ],
        ),
    ]
