# Generated by Django 5.2.15 on 2026-07-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0023_masterfiliere_masterprogramme_etudiantmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantmaster',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiantmaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='etudiantmaster',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiantmaster',
            name='statut',
            field=models.CharField(choices=[('AF', 'Admis Formation'), ('NF', 'Non Formation')], default='NF', max_length=2),
        ),
        migrations.AddField(
            model_name='etudiantmaster',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='masterprogramme',
            name='specialite',
            field=models.CharField(choices=[('QHSE', 'Management QHSE'), ('DROIT', 'Droit Privé'), ('GESTION', 'Sciences de Gestion')], default='GESTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiantmaster',
            name='niveau',
            field=models.CharField(choices=[('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='etudiantmaster',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='lmd.masterprogramme'),
        ),
        migrations.AlterField(
            model_name='etudiantmaster',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='masterprogramme',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes_master', to='lmd.filierelmd'),
        ),
    ]
