# Generated by Django 5.2.15 on 2026-07-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0024_etudiantmaster_date_naissance_etudiantmaster_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notemaster',
            unique_together={('etudiant', 'ecue')},
        ),
        migrations.CreateModel(
            name='NoteMasterHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.FloatField(default=0)),
                ('examen', models.FloatField(default=0)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.masterecue')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.etudiantmaster')),
            ],
        ),
    ]
