# Generated by Django 5.2.15 on 2026-07-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0025_alter_notemaster_unique_together_notemasterhh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatSemestreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('moyenne', models.FloatField(default=0)),
                ('credits_obtenus', models.IntegerField(default=0)),
                ('resultat', models.CharField(default='RATTRAPAGE', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmd.etudiantmaster')),
            ],
        ),
    ]
