# Generated by Django 5.2.7 on 2026-07-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0026_resultatsemestremaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecue",
            name="semestre",
            field=models.CharField(
                choices=[("S1", "Semestre 1"), ("S2", "Semestre 2")],
                default="S1",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="ue",
            name="credit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ue",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ues",
                to="lmd.filierelmd",
            ),
        ),
        migrations.AlterField(
            model_name="ue",
            name="semestre",
            field=models.CharField(
                choices=[
                    ("S1", "Semestre 1"),
                    ("S2", "Semestre 2"),
                    ("S3", "Semestre 3"),
                    ("S4", "Semestre 4"),
                    ("S5", "Semestre 5"),
                    ("S6", "Semestre 6"),
                ],
                default="S1",
                max_length=2,
            ),
        ),
    ]
