# Generated by Django 5.2.15 on 2026-08-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0027_ecue_semestre_alter_ue_credit_alter_ue_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=2),
        ),
    ]
