# Generated by Django 5.2.15 on 2026-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0028_ue_niveau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='ue',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
