# Generated by Django 5.2.15 on 2026-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0029_alter_ue_options_ue_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecue',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
    ]
