# Generated by Django 5.2.15 on 2026-08-12 09:13

import django.db.models.deletion
from django.db import migrations, models


def remplir_grandes_unites(apps, schema_editor):
    GrandeUnite = apps.get_model("lmd", "GrandeUnite")

    valeurs = {
        1: {
            "code": "UFO1",
            "niveau": "L1",
            "ordre": 1,
        },
        2: {
            "code": "UCG1",
            "niveau": "L1",
            "ordre": 2,
        },
        3: {
            "code": "USP1",
            "niveau": "L1",
            "ordre": 3,
        },
        4: {
            "code": "UFO3",
            "niveau": "L3",
            "ordre": 1,
        },
        5: {
            "code": "USP3",
            "niveau": "L3",
            "ordre": 2,
        },
        6: {
            "code": "UME3",
            "niveau": "L3",
            "ordre": 3,
        },
        7: {
            "code": "UCG3",
            "niveau": "L3",
            "ordre": 4,
        },
    }

    for grande_unite_id, data in valeurs.items():
        GrandeUnite.objects.filter(
            id=grande_unite_id
        ).update(
            code=data["code"],
            niveau=data["niveau"],
            ordre=data["ordre"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lmd", "0030_ecue_ordre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grandeunite",
            options={"ordering": ["niveau", "semestre", "ordre"]},
        ),

        migrations.AddField(
            model_name="grandeunite",
            name="code",
            field=models.CharField(
                default="ffr02",
                help_text="Ex : UFO1, UCG2, USP3",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="grandeunite",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("L1", "Licence 1"),
                    ("L2", "Licence 2"),
                    ("L3", "Licence 3"),
                ],
                default="L1",
                max_length=2,
            ),
        ),

        migrations.AddField(
            model_name="grandeunite",
            name="ordre",
            field=models.PositiveIntegerField(default=1),
        ),

        migrations.AlterField(
            model_name="grandeunite",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grandes_unites",
                to="lmd.filierelmd",
            ),
        ),

        migrations.AlterField(
            model_name="grandeunite",
            name="nom",
            field=models.CharField(
                help_text="Ex : UNITES FONDAMENTALES",
                max_length=200,
            ),
        ),

        migrations.AlterField(
            model_name="grandeunite",
            name="semestre",
            field=models.CharField(
                choices=[
                    ("S1", "Semestre 1"),
                    ("S2", "Semestre 2"),
                    ("S3", "Semestre 3"),
                    ("S4", "Semestre 4"),
                    ("S5", "Semestre 5"),
                    ("S6", "Semestre 6"),
                ],
                default="S1",
                max_length=2,
            ),
        ),

        migrations.RunPython(
            remplir_grandes_unites,
            migrations.RunPython.noop,
        ),

        migrations.AlterUniqueTogether(
            name="grandeunite",
            unique_together={
                ("code", "filiere", "niveau", "semestre")
            },
        ),
    ]