# Generated by Django 5.2.15 on 2026-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0031_alter_grandeunite_options_grandeunite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='session',
            field=models.CharField(choices=[('1', 'Session 1'), ('2', 'Session 2 (Rattrapage)')], default='1', max_length=1),
        ),
    ]
