# Generated by Django 5.2.15 on 2026-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0032_ue_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelmd',
            name='session',
            field=models.CharField(choices=[('1', 'Session 1'), ('2', 'Session 2 (Rattrapage)')], default='1', max_length=20),
        ),
    ]
