# Generated by Django 5.2.15 on 2026-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0033_alter_notelmd_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantlmd',
            name='statut',
            field=models.CharField(choices=[('AF', 'Affecté'), ('NF', 'Non Affecté')], default='NF', max_length=20),
        ),
    ]
